version: '3'
services:
  worker:
    build: .
    command: bash -c "./server.rb run"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    networks:
      - airport
networks:
  airport:
    external:
      name: airport_network
